language: node_js # 设置语言
node_js: stable # 设置相应版本
cache:
  apt: true
  directories:
  - node_modules  # 缓存不经常更改的内容
before_install:
- export TZ='Asia/Shanghai' # 更改时区
install:
- npm install
script:
- hexo clean
- hexo g
after_script:
- git clone https://${GH_REF} .deploy_git
- cd .deploy_git
- git checkout master
- cd ../
- mv .deploy_git/.git/ ./public/
- cd ./public
- git config user.name "BraveY"
- git config user.email "lsz_yky@163.com"
- git add .
- git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
- git push --force --quiet "https://${github_blog@${GH_REF}" master:master
branches:
  only:
  - hexo
env:
  global:
  - GH_REF: github.com/BraveY/BraveY.github.io.git
notifications:
  email:
  - lsz_yky@163.com
  on_success: change
  on_failure: always
